version: 0.2

phases:
  build:
    commands:
       - echo Starting Build
  post_build:
    commands:
       - mvn package
artifacts:
    files:
     - target/suchapp-0.0.1-SNAPSHOT.jar
     - appspec.yml
     - startup.sh
     - beforestart.sh
