version: 0.2

phases:
  build:
    commands:
       - echo Starting Build
  post_build:
    commands:
       - mvn package
       - aws s3 cp target/suchapp-0.0.1-SNAPSHOT.jar s3://dipander-logs-region2/suchapp-0.0.1-SNAPSHOT.jar --region us-east-1
artifacts:
    files:
     - target/suchapp-0.0.1-SNAPSHOT.jar
